vich_uploader:
  db_driver: orm

  mappings:
    product_images:
      uri_prefix: '%app.path.product_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
      namer:
        service: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
    category_images:
      uri_prefix: '%app.path.category_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.category_images%'
      namer:
        service: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true